blog/urls.py
from django.urls import path
from blog.views import BlogListView, CategoryDetailView, BlogPostDetailView, tagged_view, UpdateCommentView, DeleteCommentView

app_name = 'blog'

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='bloglist'),
    path('article/<slug:slug>/', BlogPostDetailView.as_view(), name='BlogPost-details'),
    path('tag/<slug:slug>/', tagged_view, name="tagged"),
    path('category/<slug:slug>/', CategoryDetailView, name='category_detail'),
    path('article/<int:pk>/update_comment', UpdateCommentView.as_view(), name='Update_comment'),
    path('article/<int:pk>/delete_comment', DeleteCommentView.as_view(), name='Delete_comment'),


]

vortex/urls.py
from django.contrib import admin
from django.urls import path,include
from vortex.views import Index
from vortex.views import Loginpage
from vortex.views import Registerpage
from vortex.views import Courses
from vortex.views import Contact
from vortex.views import About

from blog.views import BlogListView, CategoryDetailView, BlogPostDetailView, tagged_view, UpdateCommentView, DeleteCommentView

app_name = 'blog'

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='bloglist'),
    path('article/<slug:slug>/', BlogPostDetailView.as_view(), name='BlogPost-details'),
    path('tag/<slug:slug>/', tagged_view, name="tagged"),
    path('category/<slug:slug>/', CategoryDetailView, name='category_detail'),
    path('article/<int:pk>/update_comment', UpdateCommentView.as_view(), name='Update_comment'),
    path('article/<int:pk>/delete_comment', DeleteCommentView.as_view(), name='Delete_comment'),

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', Index.as_view(),name="index"),
    path('login/', Loginpage.as_view(),name="login"),
    path('register/', Registerpage.as_view(),name="register"),
    path('contact/', Contact.as_view(),name="contact"),
    path('courses/', Courses.as_view(),name="courses"),
    path('about/', About.as_view(),name="about"),
    
]

blog/models.py
from turtle import position
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
from datetime import datetime, date
from cloudinary.models import CloudinaryField
#from portfolio.models import Category
from taggit.managers import TaggableManager

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=100, null=True)
    
    def __str__(self):
        return self.name

class WriterProfile(models.Model):
    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE,
    )
    image = CloudinaryField('image', null=True, blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    bio = models.CharField(max_length=2000)

    def __str__(self):
        return str(self.user)

# Create your models here.
class BlogPost(models.Model):
    image = CloudinaryField('image', null=True, blank=True)
    title = models.CharField(max_length=255)
    snippet = models.CharField(max_length=255, default='snippet test')
    slug = models.SlugField(unique=True, max_length=100, null=True)
    author = models.ForeignKey(WriterProfile, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content1 = RichTextField(blank=True, null=True)
    blog_quote = models.CharField(max_length=500, blank=True)
    content2 = RichTextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)
    date_posted = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title + '|' + str(self.author)

    def get_absolute_url(self):
        return reverse('BlogPost-details', kwargs={'slug': self.slug})

class BlogComment(models.Model):
    blogpost_connected =  models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.author) + ' , ' + self.blogpost_connected.title[:40]

    def get_absolute_url(self):
        return reverse('update_comment', kwargs={'pk': self.pk})

class About(models.Model):
    image = CloudinaryField('image', null=True, blank=True)
    title = models.CharField(max_length=255)
    content1 = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title + '|' 'about'

class Roles(models.Model):
    title = models.CharField(max_length=255)
    position = models.CharField(max_length=255)

    def __str__(self):
        return self.title

base/forms.py
from django import forms
from .models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']

    def clean_username(self):
        username = self.cleaned_data.get('first_name') + self.cleaned_data.get('last_name')
        return username.lower()

blog/forms.py
from django import forms
from blog.models import BlogComment

class CommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }

base/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import BlogPost, BlogComment, Category
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from blog.forms import CommentForm, EditCommentForm
from taggit.models import Tag
from django.template.defaultfilters import slugify

###------------------- Redirect to previous page Mixin
class RedirectToProviousMixin:
    default_redirect = '/'

    def get(self, request, *args, **kwargs):
        request.session['previous_page'] = request.META.get('HTTP_REFERER', self.default_redirect)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return self.request.session['previous_page']
###################################################################################################



#####------------------ Blog list view 
class BlogListView(ListView):
    model = BlogPost
    template_name = 'blog.html'
    ordering = ['-date_posted']
    paginate_by = 8
#######################################################




#####-------------------- Blog Post Detail View
class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blogpost-details.html'


    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(BlogPostDetailView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        context["BlogPosts"] =  BlogPost.objects.all().order_by('-date_posted')[:3]
        # context["related_items"] = self.object.tags.similar_objects()[:5]
        #context['commot_tags'] = BlogPost.objects.tags.most_common()[:4]
        comments_connected = BlogComment.objects.filter(blogpost_connected=self.get_object()).order_by('-date_posted')
        context['comments'] = comments_connected
        if self.request.user.is_authenticated:
            context['form_comment'] = CommentForm(instance=self.request.user)

        return context
    
    def post(self, request, *args, **kwargs):
        new_comment = BlogComment(content=request.POST.get('content'),
                                  author=self.request.user,
                                  blogpost_connected=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)
###################################################################################################


def tagged_view(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = BlogPost.tags.most_common()[:4]
    posts = BlogPost.objects.filter(tags=tag)
    context = {
        'tag':tag,
        'posts':posts,
        'common_tags':common_tags,
    }
    return render(request, 'tagged.html', context)


#######----------------- Category Detail View
##def CategoryDetailView(request, cats):
 #   category_posts = BlogPost.objects.filter(category=cats.replace('-', ' '))
  #  return render(request, 'category_detail.html',
   #               {'cats': cats.title().replace('-', ' '), 'category_posts': category_posts})
###################################################################################################

def CategoryDetailView(request, slug):
    cat = get_object_or_404(Category, slug=slug)
    #common_tags = BlogPost.tags.most_common()[:4]
    posts = BlogPost.objects.filter(category=cat)
    context = {
        'cat':cat,
        'posts':posts,
        #'common_tags':common_tags,
    }
    return render(request, 'category_detail.html', context)



#########---------------- Delete Comment View    
class DeleteCommentView(RedirectToProviousMixin, DeleteView):
    model = BlogComment
    template_name = 'delete_comment.html'
###################################################################################################

   

#####-------------------- Update comment View
class UpdateCommentView(RedirectToProviousMixin, UpdateView):
    model = BlogComment
    template_name = 'update_comments.html'
    form_class = EditCommentForm
###################################################################################################

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="header-area header-transparent">
  <div class="main-header ">
  <div class="header-bottom  header-sticky">
  <div class="container-fluid">
  <div class="row align-items-center">
  
  <div class="col-xl-2 col-lg-2">
  <div class="logo">
  <a href="{% url 'index' %}" style="font-size:3rem;font-weight:bolder" >Vortex</a>
  </div>
  </div>
  <div class="col-xl-10 col-lg-10">
  <div class="menu-wrapper d-flex align-items-center justify-content-end">
  
  <div class="main-menu d-none d-lg-block">
  <nav>
  <ul id="navigation">
  <li class="active"><a href="{% url 'index' %}">Home</a></li>
  <li><a href="{% url 'courses' %}">Courses</a></li>
  <li><a href="{% url 'about' %}">About</a></li>
  <li><a href="{% url 'blog:bloglist' %}">Blog</a>
  </li>
  <li><a href="{% url 'contact' %}">Contact</a></li>
  
  <li class="button-header margin-left "><a href="{% url 'register' %}" class="btn">Register</a></li>
  <li class="button-header"><a href="{% url 'login' %}" class="btn btn3">Log in</a></li>
<li><div class="primary-switch" style="margin-top:1rem">
    <input type="checkbox" id="primary-switch" >
    <label for="primary-switch"></label>
    </div></li>  </ul>
  </nav>
  </div>
  </div>
  </div>
  
  <div class="col-12">
  <div class="mobile_menu d-block d-lg-none"></div>
  </div>
  </div>
  </div>
  </div>
  </div>
  </div>
  

<main>


<section class="slider-area slider-area2">
<div class="slider-active">

<div class="single-slider slider-height2">
<div class="container">
<div class="row">
<div class="col-xl-8 col-lg-11 col-md-12">
<div class="hero__caption hero__caption2">
<h1 data-animation="bounceIn" data-delay="0.2s">About us</h1>

<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'about' %}">about</a></li>
</ol>
</nav>

</div>
</div>
</div>
</div>
</div>
</div>
</section>
<div class="services-area services-area2 section-padding40">
<div class="container">
<div class="row justify-content-sm-center">
<div class="col-lg-4 col-md-6 col-sm-8">
<div class="single-services mb-30">
<div class="features-icon">
<img src="{% static 'assets/img/icon/icon1.svg' %}" alt="">
</div>
<div class="features-caption">
<h3>60+ UX courses</h3>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-8">
<div class="single-services mb-30">
<div class="features-icon">
<img src="{% static 'assets/img/icon/icon2.svg' %}" alt="">
</div>
<div class="features-caption">
<h3>Expert instructors</h3>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-8">
<div class="single-services mb-30">
<div class="features-icon">
<img src="{% static 'assets/img/icon/icon3.svg' %}" alt="">
</div>
<div class="features-caption">
<h3>Life time access</h3>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
</div>
</div>
</div>

<section class="about-area1 fix pt-10">
<div class="support-wrapper align-items-center">
<div class="left-content1">
<div class="about-icon">
<img src="{% static 'assets/img/icon/about.svg' %}" alt="">
 </div>

<div class="section-tittle section-tittle2 mb-55">
<div class="front-text">
<h2 class="">Learn new skills online with top educators</h2>
<p>The automated process all your website tasks. Discover tools and
techniques to engage effectively with vulnerable children and young
people.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Techniques to engage effectively with vulnerable children and young people.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world learning together.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world learning together. Online learning is as easy and natural.</p>
</div>
</div>
</div>
<div class="right-content1">

<div class="right-img">
<img src="{% static 'assets/img/gallery/about3.png' %}" alt="">
<div class="video-icon">
<a class="popup-video btn-icon" href="https://www.youtube.com/watch?v=up68UAfH0d0"><i class="fas fa-play"></i></a>
</div>
</div>
</div>
</div>
</section>


<div class="topic-area section-padding40">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-7 col-lg-8">
<div class="section-tittle text-center mb-55">
<h2>Explore top subjects</h2>
</div>
</div>
</div>
<div class="row">
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic1.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic2.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
 </div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic3.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic4.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic5.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic6.png' %}" alt="">
 <div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic7.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic8.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row justify-content-center">
<div class="col-xl-12">
<div class="section-tittle text-center mt-20">
<a href="courses.html" class="border-btn">View More Subjects</a>
</div>
</div>
</div>
</div>
</div>


<section class="about-area3 fix">
<div class="support-wrapper align-items-center">
<div class="right-content3">

<div class="right-img">
<img src="{% static 'assets/img/gallery/about3.png' %}" alt="">
</div>
</div>
<div class="left-content3">

<div class="section-tittle section-tittle2 mb-20">
<div class="front-text">
<h2 class="">Learner outcomes on courses you will take</h2>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Techniques to engage effectively with vulnerable children and young people.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world
learning together.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world learning together.
Online learning is as easy and natural.</p>
</div>
</div>
</div>
</div>
</section>


<section class="team-area section-padding40 fix">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-7 col-lg-8">
<div class="section-tittle text-center mb-55">
<h2>Community experts</h2>
</div>
</div>
</div>
<div class="team-active">
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team1.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Urela</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team2.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Uttom</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team3.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Shakil</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team4.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Arafat</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team3.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. saiful</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
</div>
</section>

</main>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="header-area header-transparent">
  <div class="main-header ">
  <div class="header-bottom  header-sticky">
  <div class="container-fluid">
  <div class="row align-items-center">
  
  <div class="col-xl-2 col-lg-2">
  <div class="logo">
  <a href="{% url 'index' %}" style="font-size:3rem;font-weight:bolder" >Vortex</a>
  </div>
  </div>
  <div class="col-xl-10 col-lg-10">
  <div class="menu-wrapper d-flex align-items-center justify-content-end">
  
  <div class="main-menu d-none d-lg-block">
  <nav>
  <ul id="navigation">
  <li class="active"><a href="{% url 'index' %}">Home</a></li>
  <li><a href="{% url 'courses' %}">Courses</a></li>
  <li><a href="{% url 'about' %}">About</a></li>
  <li><a href="{% url 'blog:bloglist' %}">Blog</a>
  </li>
  <li><a href="{% url 'contact' %}">Contact</a></li>
  
  <li class="button-header margin-left "><a href="{% url 'register' %}" class="btn">Register</a></li>
  <li class="button-header"><a href="{% url 'login' %}" class="btn btn3">Log in</a></li>
<li><div class="primary-switch" style="margin-top:1rem">
    <input type="checkbox" id="primary-switch" >
    <label for="primary-switch"></label>
    </div></li>  </ul>
  </nav>
  </div>
  </div>
  </div>
  
  <div class="col-12">
  <div class="mobile_menu d-block d-lg-none"></div>
  </div>
  </div>
  </div>
  </div>
  </div>
  </div>
  

<main>

<section class="slider-area slider-area2">
<div class="slider-active">

<div class="single-slider slider-height2">
<div class="container">
<div class="row">
<div class="col-xl-8 col-lg-11 col-md-12">
<div class="hero__caption hero__caption2">
<h1 data-animation="bounceIn" data-delay="0.2s">Contact us</h1>

<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'contact' %}">Contact</a></li>
</ol>
</nav>

</div>
</div>
</div>
</div>
</div>
</div>
</section>

<section class="contact-section">
<div class="container">
<div class="d-none d-sm-block mb-5 pb-4">

<script>
                    function initMap() {
                        var uluru = {
                            lat: -25.363,
                            lng: 131.044
                        };
                        var grayStyles = [{
                            featureType: "all",
                            stylers: [{
                                saturation: -90
                            },
                            {
                                lightness: 50
                            }
                            ]
                        },
                        {
                            elementType: 'labels.text.fill',
                            stylers: [{
                                color: '#ccdee9'
                            }]
                        }
                        ];
                        var map = new google.maps.Map(document.getElementById('map'), {
                            center: {
                                lat: -31.197,
                                lng: 150.744
                            },
                            zoom: 9,
                            styles: grayStyles,
                            scrollwheel: false
                        });
                    }
                </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&amp;callback=initMap">
                </script>
</div>
<div class="row">
<div class="col-12">
<h2 class="contact-title">Get in Touch</h2>
</div>
<div class="col-lg-8">
<form class="form-contact contact_form" action="https://preview.colorlib.com/theme/courses/contact_process.php" method="post" id="contactForm" novalidate="novalidate">
<div class="row">
<div class="col-12">
<div class="form-group">
<textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder=" Enter Message"></textarea>
</div>
</div>
<div class="col-sm-6">
<div class="form-group">
<input class="form-control valid" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder="Enter your name">
</div>
</div>
<div class="col-sm-6">
<div class="form-group">
<input class="form-control valid" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder="Email">
</div>
</div>
<div class="col-12">
<div class="form-group">
<input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder="Enter Subject">
</div>
</div>
</div>
<div class="form-group mt-3">
<button type="submit" class="button button-contactForm boxed-btn">Send</button>
</div>
</form>
</div>
<div class="col-lg-3 offset-lg-1">
<div class="media contact-info">
<span class="contact-info__icon"><i class="ti-home"></i></span>
<div class="media-body">
<h3>Buttonwood, California.</h3>
<p>Rosemead, CA 91770</p>
</div>
</div>
<div class="media contact-info">
<span class="contact-info__icon"><i class="ti-tablet"></i></span>
<div class="media-body">
<h3>+1 253 565 2365</h3>
<p>Mon to Fri 9am to 6pm</p>
</div>
</div>
<div class="media contact-info">
<span class="contact-info__icon"><i class="ti-email"></i></span>
<div class="media-body">
<h3><a href="https://preview.colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="62111712120d101622010d0e0d100e0b004c010d0f">[email&#160;protected]</a></h3>
<p>Send us your query anytime!</p>
</div>
</div>
</div>
</div>
</div>
</section>

</main>

{% endblock %}

templates/delete_comment.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="col-md-3" style='padding:30px;'>
	<div class="blog-entry justify-content-end" data-aos="fade-down" data-aos-duration="1000" data-aos-delay="100">
	
	<div class="list-team d-flex align-items-center">
	<div class="d-flex align-items-center">
	
	</div>
	<div class="text-right ion">
	
	</div>
	</div>
	<div class="text">
	<h3 class="heading mb-3">Do you really want to delete these records? This process cannot be undone.</h3>
	<form method="post">
		{% csrf_token %}
		<input type="submit" value="Delete Comment" class="btn py-3 px-4 btn-darken">
	</form>

	</div>
	</div>
	</div>

{% endblock %}